### ISSUE TITLE
VisualBoyAdvance-M automatic save type detection doesn't work

### ISSUE THREAD

**Issue by djmaximum17** [jturcotte/chiptrack#6]
I wonder if this was intentional, because it only seems to work with mGBA. other emulators like VBA-M just sit at a blank screen when loading the rom. is there some sort of checksum that prevents it from starting in other GBA emulators?

**Comment by jturcotte** [comment]
This is not intentional, I test mostly with mGBA but 0.4 also runs for me in VisualBoyAdvance on Linux.

It's possible that the code does something that the emulator isn't expecting and it makes the game crash inside while mGBA and real hardware would be less sensitive to the issue.

**Comment by jturcotte** [comment]
I just tried VisualBoyAdvance-M 2.1.11 on Linux and it also works, which version are you using?

**Comment by jturcotte** [comment]
OK I can reproduce the issue if I remove the .sav file I had there, let me have a look over the next few days.

**Comment by djmaximum17** [comment]
update, I forgot VBA-M has different save types, changed it to SRAM and it works.

**Comment by jturcotte** [comment]
Ah awesome!
They seem to look for text in the ROM for auto-detection to work, I'll try to get it to work out of the box with the Automatic save type.

https://github.com/visualboyadvance-m/visualboyadvance-m/blob/000c7f854ccb5fd4191abdb4ce3f3946247e9256/src/core/gba/gbaFlash.cpp#L49-L52

**Comment by djmaximum17** [comment]
I had a look in the retroarch VBA-M and it doesn't have settings to change the save type

**Comment by jturcotte** [comment]
I'll try to do a release soon with the few fixes on the main branch, but you can try this build meanwhile: [chiptrack-dev.gba.zip](https://github.com/user-attachments/files/17483119/chiptrack-dev.gba.zip)

**Comment by djmaximum17** [comment]
still boots to a blank screen, (using retroarch)
![Screenshot 2024-10-23 at 1 39 51 PM](https://github.com/user-attachments/assets/aac58d32-a4dd-445b-a22e-f78438024a68)

**Comment by jturcotte** [comment]
What core version is it?

I tried and chiptrack-0.4.gba doesn't load in the VBA-M 2.1.3 core that retroarch downloaded, as you initially reported, but the fixed chiptrack-dev.gba loads in cores mGBA, VBA-M and VBA Next for me.

**Comment by djmaximum17** [comment]
turns out I accidentally disabled the background layer in the core options menu, its working now.
![Screenshot 2024-10-23 at 2 04 08 PM](https://github.com/user-attachments/assets/40a6c34c-818d-4676-912b-cf5fdf0c0967)
